# Generated by Django 4.2.23 on 2025-09-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_app', '0002_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the bank belongs to the user and has been verified'),
        ),
    ]
