# Generated by Django 4.2.23 on 2025-09-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_app', '0003_bankaccount_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank',
            new_name='bank_code',
        ),
    ]
