# Generated by Django 4.2.23 on 2025-09-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_app', '0004_rename_bank_bankaccount_bank_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='unique_user_bank_account',
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('user', 'bank_code', 'account_number'), name='unique_user_bank_account'),
        ),
    ]
