import requests
import base64
import hmac
import hashlib
import time


class HashAlgo:
    algo="HS256"
    func=hashlib.sha256

hash_algorithm = HashAlgo()

Secret = "nlt2fz*q*&+fj0*e$+vj2&l=5(%uw)rg0u6d7dt0c#%*pnuna3"


class TokenClient:
    def __init__(self, base_url):
        self.base_url = base_url

    def get_tokens(self, username, password):
        url = f"{self.base_url}/api/v1/token/"
        data = {"username": username, "password": password}
        response = requests.post(url, data=data)
        if response.status_code == 200:
            return response.json()
        else:
            raise Exception(f"Failed to get tokens: {response.status_code} - {response.text}")

    def refresh_access_token(self, refresh_token):
        url = f"{self.base_url}/api/v1/token/refresh/"
        data = {"refresh": refresh_token}
        response = requests.post(url, data=data)
        if response.status_code == 200:
            return response.json()
        else:
            raise Exception(f"Failed to refresh access token: {response.status_code} - {response.text}")


def make_request_gra_gra(self, endpoint, request_body_dict)
    # Convert the header and payload to JSON strings
    # This is basicaly what the server does to generate the access token
    # how ever one I prefer to just use the token generated by teh server and let it just do the work
    Header = str({
        "alg": HashAlgo.algo,
        "typ": "JWT"
    })

    Payload = str({
        "id"  : 1,
        "user_id": user_id,
        # "iat": int(time.time()),
        # "exp": int(time.time()) + 3600,  # Token expires in 1 hour
        "token_type": "access",
        "jti": hashlib.sha256(str(time.time()).encode()).hexdigest(),
        # "refresh_exp": int(time.time()) + 86400  # Refresh token expires in 1 day
    })

    # Encode the header and payload using Base64URL encoding
    Base64UrlEncodedHeader = base64.urlsafe_b64encode(
        HeaderJson.encode()
    ).strip(b'=').decode()

    Base64UrlEncodedPayload = base64.urlsafe_b64encode(
        PayloadJson.encode()
    ).strip(b'=').decode()

    # Concatenate the encoded header and payload with a period (.)
    UnsignedToken = Base64UrlEncodedHeader + "." + Base64UrlEncodedPayload

    # Create the signature using HMAC-SHA256 and the secret key
    Signature = hmac.new(Secret.encode(), UnsignedToken.encode(), hashlib.sha256).hexdigest()

    # Concatenate the encoded header, encoded payload, and signature with periods (.)
    JWT_Token = Base64UrlEncodedHeader + "." + Base64UrlEncodedPayload + "." + Signature

    # Define the request headers
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {JWT_Token}"
    }

    response = requests.post(endpoint, json=request_body_dict, headers=headers)
    
    return response.json()


def make_request(self, endpoint, request_body_dict, access_token):

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {access_token}"
    }

    response = requests.post(endpoint, json=request_body_dict, headers=headers)
    
    return response.json()




def test():
    # Example usage:
    base_url = "http://localhost:8000"
    client = TokenClient(base_url)

    # Example for getting tokens
    username = "admin"
    password = "1234"
    tokens = client.get_tokens(username, password)
    print("Tokens:", tokens)

    # Example for refreshing access token
    refresh_token = "your_refresh_token"
    new_tokens = client.refresh_access_token(refresh_token)
    print("New Tokens:", new_tokens)

