# Generated by Django 4.2.24 on 2025-09-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_stock_product_images_product_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('retail', 'Retail / Direct Buy'), ('dropshipping', 'Dropshipping / Preorder')], default='retail', max_length=20),
        ),
    ]
