# Generated by Django 4.2.23 on 2025-08-15 06:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210317_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2348102319760', max_length=128, region='NG', unique=True),
            preserve_default=False,
        ),
    ]
