# Generated by Django 4.2.23 on 2025-08-16 07:15

from django.db import migrations, models
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_email_verified_user_is_phone_number_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_secret',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_secret',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twofa_otp_secret',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=32, null=True),
        ),
    ]
