# Generated by Django 4.2.23 on 2025-08-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_otp_secret_user_email_otp_secret_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twofa_otp_secret',
            new_name='two_factor_otp_secret',
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_trials',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_trials',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_otp_trials',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
