# Generated by Django 4.2.23 on 2025-08-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_twofa_otp_secret_user_two_factor_otp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
