# Generated by Django 4.2.23 on 2025-08-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_email_otp_counter_user_phone_otp_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
