# Generated by Django 4.2.23 on 2025-08-19 04:07

from django.db import migrations, models
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_email_otp_expires_at_user_phone_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_otp_counter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_counter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_secret',
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_hash',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_hash',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=32, null=True),
        ),
    ]
