# Generated by Django 4.2.23 on 2025-08-20 00:25

from django.db import migrations, models
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_recoverycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_otp_hash',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_otp_hash',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_otp_secret',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=50, null=True),
        ),
    ]
