# Generated by Django 4.2.23 on 2025-08-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_email_otp_hash_alter_user_phone_otp_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
