# Generated by Django 4.2.23 on 2025-08-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bvn_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_liveness_check_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Not Verified'), (1, 'Email / Phone'), (2, 'Liveness Check'), (3, 'BVN Verified')], default=0),
        ),
    ]
