# Generated by Django 4.2.23 on 2025-08-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_bvn_verified_user_is_liveness_check_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_customer_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_customer_verified',
            field=models.BooleanField(default=False),
        ),
    ]
