# Generated by Django 4.2.23 on 2025-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_paystack_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paystack_dva_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_dva_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
