# Generated by Django 4.2.23 on 2025-08-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_paystack_dva_json_user_paystack_dva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paystack_dva_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_dva_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_dva_bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_dva_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_dva_bank_slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_dva_currency',
            field=models.CharField(blank=True, default='NGN', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_dva_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
