# Generated by Django 4.2.23 on 2025-09-05 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_paystack_dva_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pub_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
