# Generated by Django 4.2.23 on 2025-09-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_pub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn_hashed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
