# Generated by Django 4.2.24 on 2025-10-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0023_user_address_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, default='NG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='countries_plus.country'),
        ),
    ]
