# Generated by Django 4.2.24 on 2025-10-29 12:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0024_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_registered_with',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='countries_plus.country'),
        ),
    ]
