# Generated by Django 4.2.24 on 2025-10-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_country_registered_with_alter_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
