# Generated by Django 4.2.24 on 2025-10-30 23:07

from django.db import migrations, models
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_user_address_remove_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_hash',
            field=models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_trials',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
