# Generated by Django 4.2.24 on 2025-11-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.URLField(blank=True, null=True, verbose_name='PictureUrl'),
        ),
    ]
