# Generated by Django 4.2.26 on 2025-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_onboarding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding_status',
            field=models.CharField(choices=[('needs_basic_information', 'Needs Basic Information'), ('needs_email_verification', 'Needs Email Verification'), ('needs_phone_verification', 'Needs Phone Verification'), ('needs_user_type', 'Needs User Type Selection'), ('needs_profile_username', 'Needs Profile Username Completion'), ('needs_profile_picture', 'Needs Profile Picture Upload'), ('needs_location_info', 'Needs Location Information'), ('needs_store_info', 'Needs Store Information'), ('needs_kyc_identity_verification', 'Needs KYC Identity Verification'), ('needs_bank', 'Needs Bank Information'), ('needs_vendor_plan', 'Needs Vendor Plan Selection'), ('completed', 'Completed')], default='needs_basic_information', max_length=50),
        ),
    ]
