# Generated by Django 4.2.24 on 2025-09-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_stock_product_images_product_seller_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouporder',
            options={'ordering': ['-batch_number']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='grouporder',
            name='batch_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouporder',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('fulfilled', 'Fulfilled')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='group_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.grouporder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='target_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='grouporder',
            unique_together={('product', 'batch_number')},
        ),
        migrations.RemoveField(
            model_name='grouporder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='grouporder',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='grouporder',
            name='orders',
        ),
    ]
